---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helics
  namespace: helics
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: helics
  chart:
    git: git@github.com:tahirjaved1/simulation-thesis.git
    ref: main
    path: charts/ghosts
  values:
    image:
      repository: l191852/helics-simulation
      tag: latest
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    service:
      type: ClusterIP
    mariadb:
      master:
        persistence:
          enabled: false
